### ISSUE TITLE
Resource IDs

### ISSUE THREAD

**Issue by scrook** [scrook/neuroml-db#102]
Do Resources (ModelDB, OSB) have an associated RRID from SciCrunch? These should be available. Not sure how to use them but might end up using these as a primary key for the resources?

**Comment by JustasB** [comment]
Not currently. I can add those to each resource entry. Need to think about where a link that points back to SciCrunch should be displayed -- currently the resource logos point to the model on that resource's web page.

**Comment by scrook** [comment]
I think we just need a record of the RRID number. That's it. These are numbers that people use to reference projects.

**Comment by JustasB** [comment]
Ok, I'll add the RRIDs to each resource and then display the RRIDs in a row in the model view

**Comment by JustasB** [comment]
The RRIDs are ready for viewing on spike: http://spike.asu.edu:5000/model_info?model_id=NMLCH000001

Each resource will have a link underneath its logo, which, when clicked, will take to scicrunch page of that resource:

![image](https://user-images.githubusercontent.com/10732358/32803221-0d65f734-c940-11e7-8a4c-5134f5fa3a6b.png)

**Comment by scrook** [comment]
Do you think this detracts from someone clicking on the icon to go to the model page on ModelDB or OSB? Worried they won't realize they can do that. Do you have any other ideas for how to display. Also, I think maybe the neurolex id and keywords should appear before the NeuroML files. I find them very helpful but they are way down at the bottom.

**Comment by scrook** [comment]
Why is direct link to model needed? Just takes to same page.

**Comment by JustasB** [comment]
Hmmm I see. Need to think about how to best display both the model link and the link to SciCrunch.

I'll remove the direct model link.. it's a leftover from a while back.

**Comment by JustasB** [comment]
Ok the above changes are visible on live site: https://neuroml-db.org/model_info?model_id=NMLCL001132

Take a look and let me know if the new Resource layout works for you better.

**Comment by scrook** [comment]
Looks good. Let's try this out. I think the keywords should be spelled out. I assume it is actually olfactory bulb not OB.

**Comment by JustasB** [comment]
Ok sounds good. The acronyms in the keyword are just in addition to the spelled out full name. So queries like "mob mitral" will match the search as well.

**Comment by scrook** [comment]
I just mean when listing on model page.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JustasB** [comment]
That would be a bit of work -- to get the mapping between all the acronyms that appear in the keyword column across all models and their full spellings. Not sure what would be the gain... 

I had moved the keyword field down the model view so that the acronyms would not be so prominent, while still serving as hints for the DB search engine.

Are you sure that's what you want?

**Comment by scrook** [comment]
No, because I don't understand the problem. Let's wait and talk about it later in person.


Sharon Crook
Professor
School of Mathematical and Statistical Sciences
School of Life Sciences
Arizona State University

Mailcode: 1804
Tempe, Arizona 85287-1804
email: sharon.crook@asu.edu
phone: 480-965-0403
web: https://iconlab.asu.edu
twitter: @SharCrook

________________________________________
