### ISSUE TITLE
Clean up Spike

### ISSUE THREAD

**Issue by scrook** [scrook/neuroml-db#50]
We need a plan for cleaning up spike. It is too confusing to have a lot of old code there.

**Comment by JustasB** [comment]
Just did major cleanup of spike. Dendrite has all the sites, with spike having cloned copies for testing. The folders on spike are all organized to match the structure on dendrite. Also wrote scripts that, when run, will pull down the latest versions from the "production" branch into dendrite, and from "master" branch into spike. To move a change from spike, e.g. after testing, into dendrite will involve merging those changes from master branch into production branch via github UI.

One piece left to automate is automatic pull down from the branches when changes are checked into them. I'll need you to make some changes in github repo to enable this.  I'll create an issue describing what's needed.
