### ISSUE TITLE
Vineel will work on code that creates neuroml files from metadata and xml files in channelpedia 

### ISSUE THREAD

**Issue by JustasB** [scrook/neuroml-db#67]

**Comment by pgleeson** [comment]
Hi @JustasB, Vineel,

Please note this file: https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/Channelpedia/ChannelpediaToNeuroML2.py which pulls info from Channelpedia and puts it with metadata into nml2 files.
