### ISSUE TITLE
Rajesh will work on code that creates neuroml files from xml files in HBP

### ISSUE THREAD

**Issue by JustasB** [scrook/neuroml-db#68]

**Comment by pgleeson** [comment]
Hi @JustasB, Rajesh, @scrook,

This file: https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/parser/ParseAll.py generates NML2 files from the BBP cell files. See https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/tree/master/NMC and  https://bbp.epfl.ch/nmc-portal/downloads. More metadata can certainly be added to the generated files.
