### ISSUE TITLE
Validating the NML files from HBP

### ISSUE THREAD

**Issue by vrjdev** [scrook/neuroml-db#72]
Validate the cell and channel file.

@scrook  @JustasB

**Comment by JustasB** [comment]
@vrjdev You can use the -nogui flag to auto-close NEURON when the simulation is finished:

http://stackoverflow.com/questions/36562359/simulation-done-finished-event-in-jneuroml

**Comment by vrjdev** [comment]
@JustasB  when we use the option nogui it exits when there is no error in the simulation. If any error exists it doesnt close. Its an observation I have seen while running the program.

**Comment by pgleeson** [comment]
@vrjdev Can you open an issue here: https://github.com/NeuroML/jNeuroML/issues with this or any other problems you have, giving more details and ideally an example that illustrates the error?
