### ISSUE TITLE
Installing Neuron

### ISSUE THREAD

**Issue by vrjdev** [scrook/neuroml-db#73]
Run Lems file with Neuron.
Link : https://www.neuron.yale.edu/neuron/
Command : jnml NMC.NeuronML2/LEMS_L1_DAC_bNAC219_1.xml -neuron -run

@JustasB @scrook

**Comment by vrjdev** [comment]
Trying to install neuron. But stuck with the nopython: on error. Trying to fix it.

Also tried to install pyneuroml. The issue was airspeed is not installed previously.Saw the code and downloaded the airspeed repo and rerun the setup and pyneuroml is installed properly.

@JustasB @scrook

**Comment by pgleeson** [comment]
@vrjdev glad you got pyNeuroML installed. If you install libNeuroML too, make sure it's the version in the development branch.

For Neuron, did you use the --with-nrnpython option when building it as outlined here: https://www.neuron.yale.edu/neuron/download/compile_linux

**Comment by vrjdev** [comment]
@pgleeson @scrook @JustasB Neuron is working and the commands are executing properly.

Issues are:
1)Airspeed waasnt installed during Pyneuroml installation automatically.
2) For neuron we need to export both PYTHONPATH and PYTHONHOME. and 
used "sudo ln -s /usr/lib/python2.7/plat-*/_sysconfigdata_nd.py /usr/lib/python2.7/" above command to solve sysconfigdata problem.

The issue can be closed now.
