### ISSUE TITLE
Check if neuromldb.refers.reference_resource column is still needed

### ISSUE THREAD

**Issue by JustasB** [scrook/neuroml-db#78]
The column appears to be a left-over from last year, and appears to store the same information as in reference_resource_id. This should be checked if it is still needed, and removed if not.

**Comment by scrook** [comment]
I have not idea. Check with Suzanne on this.

**Comment by dietrichasuedu** [comment]
Justas and I met yesterday and put this issue in to remind us to look into it. Right now, the column is repeating the name of the resource.

**Comment by scrook** [comment]
Ok, no problem. Glad things are going ok.

**Comment by JustasB** [comment]
Yes, leftover. Removed in latest version
