### ISSUE TITLE
Decide what to do with multiple HBP models of the same cell 

### ISSUE THREAD

**Issue by JustasB** [scrook/neuroml-db#79]
The HBP cell models contain 5 instances, each one with different morphologies. We need to decide if we want to put each .nml file as a different model, or to combine the 5 .nml files for each cell into one model.

**Comment by scrook** [comment]
Sorry, thought I already replied to this. I think we should do five different models but somehow indicate which one through a name and comment. How are the morphologies labeled?

**Comment by JustasB** [comment]
@scrook Ok, we can keep all, each as separate model.  CC: @dietrichasuedu 

The HBP files use a different ending for the file name to indicate the different morphology. All cells end with _1.nml, _2.nml, .... _5.nml. 

So maybe we could append "Morphology 1", "Morphology 2", etc... to each cell model's name in our DB.
